Compiled from "DealWithExceptionForJVM.java"
public class com.jike_time.������java�����.DealWithExceptionForJVM {
  public com.jike_time.������java�����.DealWithExceptionForJVM();
    Code:
       0: aload_0
       1: invokespecial #1                  // Method java/lang/Object."<init>":()V
       4: return

  public static void main(java.lang.String[]);
    Code:
       0: invokestatic  #2                  // Method mayThrowException:()V
       3: goto          11
       6: astore_1                          // 将一个数值从操作数栈存储到局部变量表的指令
       7: aload_1
       8: invokevirtual #4                  // Method java/lang/Exception.printStackTrace:()V
      11: return
    Exception table: // 异常表：一个方法含有一个异常表
       from    to  target type
           0     3     6   Class java/lang/Exception


    // from 指针和 to 指针标示了该异常处理器所监控的范围，如[0-3)
    // target 指针则指向异常处理器的起始位置
}
